//basic text saved to progmem and not ram
PROGMEM char const basic1[] =":";
PROGMEM char const basic2[] ="0";
PROGMEM char const basic3[] =" ";
PROGMEM char const basic4[] ="Sun";
PROGMEM char const basic5[] ="Mon";
PROGMEM char const basic6[] ="Tue";
PROGMEM char const basic7[] ="Wed";
PROGMEM char const basic8[] ="Thu";
PROGMEM char const basic9[] ="Fri";
PROGMEM char const basic10[] ="Sat";
PROGMEM char const basic11[] ="/";
PROGMEM char const basic12[] ="/20";
PROGMEM char const basic13[] ="selected";
PROGMEM char const basic14[] ="F";
PROGMEM char const basic15[] ="C";
PROGMEM char const basic16[] ="20 and 120 degrees F";
PROGMEM char const basic17[] ="0 and 49 degrees C";
PROGMEM char const basic18[] ="selected=\"selected\"";
PROGMEM char const basic19[] ="On";
PROGMEM char const basic20[] ="Off";
PROGMEM char const basic21[] ="disabled";
PROGMEM char const basic22[] ="readonly";
PROGMEM char const basic23[] ="checked";
PROGMEM char const basic24[] ="x-icon";
PROGMEM char const basic25[] ="bmp";
PROGMEM char const basic26[] ="/green.png";
PROGMEM char const basic27[] ="/red.png";
PROGMEM char const basic28[] ="/on.png";
PROGMEM char const basic29[] ="/off.png";
PROGMEM char const basic30[] ="<tr><td colspan=\"2\"><font color = \"red\"><b><center>Invalid Entry!</center></b></font></td></tr>";
PROGMEM char const basic31[] ="2.0: 6/8/2016";
PROGMEM char const basic32[] =".";
PROGMEM char const basic33[] ="  ";
PROGMEM char const basic34[] =""
"<Table border = \"1\">"
			"<tr>"
				"<td align = \"center\">Date</td>"
				"<td align = \"center\">Time</td>"
				"<td align = \"center\">Cold Side Ground Temperature</td>"
				"<td align = \"center\">Middle Ground Temperature</td>"
				"<td align = \"center\">Hot Side Ground Temperature</td>"
				"<td align = \"center\">Average Ambient Temperature</td>"
				"<td align = \"center\">Average Humidity</td>"
				"<td align = \"center\">Cold Side Ground Heater Status</td>"
				"<td align = \"center\">Middle Ground Heater Status</td>"
				"<td align = \"center\">Hot Side Ground Heater Status</td>"
				"<td align = \"center\">Humidifier Status</td>"
				"<td align = \"center\">Heat Lamp Status</td>"
				"<td align = \"center\">UV Light Status</td>"
			"</tr>";
PROGMEM char const basic35[] ="<tr><td colspan = \"2\" align = \"center\"><font color = \"red\"><b>SD Card Found and formatted but not accessible - Please check SD Card</b></font></td></tr>";
PROGMEM char const basic36[] ="<tr><td colspan = \"2\" align = \"center\"><font color = \"red\"><b>Please check SD Card, SD Card Found but not functional... Is It Formatted?</b></font></td></tr>";
PROGMEM char const basic37[] ="<tr><td colspan = \"2\" align = \"center\"><font color = \"red\"><b>Please check SD Card, NO SD CARD FOUND!</b></font></td></tr>";
PROGMEM char const basic38[] ="SD1";
PROGMEM char const basic39[] ="SD2";
PROGMEM char const basic40[] ="SDHC";
PROGMEM char const basic41[] ="N/A";
PROGMEM char const basic42[] ="px;";
PROGMEM char const basic43[] ="0px;";
PROGMEM char const basic44[] ="<table height=\"14%\" border=\"0\">";
PROGMEM char const basic45[] ="<tr><td align=\"right\"><a href=\"";
PROGMEM char const basic46[] ="\" target=\"blank\">";
PROGMEM char const basic47[] ="</a></td><td align=\"left\">&nbsp;&nbsp;File Size: ";
PROGMEM char const basic48[] =" Kilobytes (KB)";
PROGMEM char const basic49[] ="</td></tr>";
PROGMEM char const basic50[] ="</table>";
PROGMEM char const basic51[] ="<select name = \"delete\">";
PROGMEM char const basic52[] ="<option value=\"";
PROGMEM char const basic53[] ="\">";
PROGMEM char const basic54[] ="</option>";
PROGMEM char const basic55[] ="GOOD";
PROGMEM char const basic56[] ="FAILED";
PROGMEM const char * const basic_table[] = 	   
{   
  basic1,basic2,basic3,basic4,basic5,basic6,basic7,basic8,basic9,basic10,basic11,basic12,basic13,basic14,basic15,basic16,basic17,basic18,basic19,basic20,
  basic21,basic22,basic23,basic24,basic25,basic26,basic27,basic28,basic29,basic30,basic31,basic32,basic33,basic34,basic35,basic36,basic37,basic38,basic39,
  basic40,basic41,basic42,basic43,basic44,basic45,basic46,basic47,basic48,basic49,basic50,basic51,basic52,basic53,basic54,basic55,basic56};

// HTML Header for pages

PROGMEM char const content_main_header[] = "HTTP/1.1 200 OK\r\n"
"Server: arduino\r\n"
"Cache-Control: no-store, no-cache, must-revalidate\r\n"
"Connection: keep-alive\r\n"
"Content-type: text/html\r\n"
"\r\n";

/********************************************
content_main_top
********************************************/

PROGMEM char const content_main_top[] = ""
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">"
"<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">"
"<head>"
"<title>Automated Reptile Environment Control System</title>"
"<style>"
"body {font-family: Verdana, Arial, sans-serif;background: #fff;margin: 0px auto;padding: 0 0 20px 0;}"
"#title {background: #ffffff;padding: 5px;font-weight: bolder;color: #000000;height: auto;border-bottom-style: solid;border-bottom-color: #000000;margin-left: 10px;margin-right: 10px;}"
"#title .right {float: center;width: auto;text-align: center;	font-size: 50px;}"
"#page {background: #ffffff;	padding: 4px;	font-weight: bolder;	color: #000000;	margin-bottom: 5px;	height: auto;	border-bottom-style: none;	margin-left: 10px;	margin-right: 10px;}"
"#page .center {width: auto;	text-align: center;	font-size: 35px;}"
"#attributes {	background: #ffffff;	padding: 0px;	font-weight: bolder;	color: #000000;	height: auto;	width:100%}"
"#menu {float: left;	width: 150px;	padding-right: 20px;	margin-left: 10px;	margin-right: 10px;	height: 100%;}"
"#menu a {width: 140px;	display: block;	color: white;	padding: 8px;	font-weight: bold;	border-bottom: 1px solid #fff;	text-decoration: none;	background-color: #0066FF;}"
"#menu a:hover {background-color: #0000FF;	cursor:pointer;}"
"* {	margin: 0;}"
"html, body {	height: 100%;}"
".wrapper {	min-height: 100%;	height: auto !important;	height: 100%;	margin: 0 auto -4em;}"
".footer, .push {	height: 4em;}"
"</style>"
"</head>";

/********************************************
content_main_menu
********************************************/

PROGMEM char const content_main_menu[] = "";
  
/********************************************
content_main_footer
********************************************/
  
PROGMEM char const content_main_footer[] = "</body><HEAD><META HTTP-EQUIV=\"PRAGMA\" CONTENT=\"NO-CACHE\"></HEAD></html>";

/********************************************
PAGE 1 DATA
********************************************/

PROGMEM char const http_uri1[] = "/";
PROGMEM char const content_title1[] = "";
PROGMEM char const content_page1[] = ""
"<body>"
"<center>"
"<div class=\"wrapper\"><div id=\"title\"><p><span id=\"hello\">&nbsp;</span></p><div id=\"attributes\">"
"<table width=\"100%\" border=\"0\" bordercolor=\"#FFFFFF\" bgcolor=\"#0066FF\">"
  "<tr>"
    "<td width=\"271\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"version\">Firmware Version: \002 </span></div></td>"
    "<td width=\"359\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"builddate\">Ip Address: \002 </span></div></td>"
    "<td width=\"191\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"date\"> \002 </span></div></td>"
    "<td width=\"176\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"time\"> \002 </span></div></td>"
  "</tr>"
"</table>"
"</div></div>"
"<div id=\"menu\">"
  "<a href=\"/\">System Overview</a>"
  "<a href=\"/page2\">Temperature Adjust</a>"
  "<a href=\"/page3\">Humidity Adjust</a>"
  "<a href=\"/page4\">Date/Time Adjust</a>"
  "<a href=\"/page5\">Data Logging Adjust</a>"
  "<a href=\"/page6\">View Recorded Data</a>"
  "<a href=\"/page7\">I/O Setup</a>"
  "<a href=\"/page8\">Network Setup</a>"
  "<a href=\"/page9\">System Information</a></div><div></div>"
"<!-- content -->"
  "<center><b><font size = 10>Automated Reptile Environment Control System<br>System Main</font></b></center><br><p>&nbsp;</p>"
  "<div style=\"margin-left: 250px; margin-right: 10px;\">"
    "<table width=\"53%\" height=\"14%\" border=\"1\">"
      "<tr>"
        "<th height=\"10%\" colspan=\"9\" class=\"style42\" scope=\"col\"> Relay Status </th>"
       "</tr>"
       "<tr>"
         "<td width=\"20%\"><div align=\"center\" class=\"style43\"><strong>Cold Side Heater<br>Relay 1</strong></div></td>"
         "<td width=\"20%\"><div align=\"center\" class=\"style43\"><strong>Middle Heater<br>Relay 2</strong></div></td>"
         "<td width=\"20%\"><div align=\"center\" class=\"style43\"><strong>Hot Side Heater<br>Relay 3</strong></div></td>"
         "<td width=\"20%\"><div align=\"center\" class=\"style43\"><strong>Heat Lamp<br>Relay 4</strong></div></td>"
         "<td width=\"20%\"><div align=\"center\" class=\"style43\"><strong>UV Light<br>Relay 5</strong></div></td>"
         "<td width=\"20%\"><div align=\"center\" class=\"style43\"><strong>Humidifier<br>Relay 6</strong></div></td>"
       "</tr>"
       "<tr>"
         "<td><div align=\"center\" class=\"style44\" id=\"img1\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
         "<td><div align=\"center\" class=\"style44\" id=\"img2\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
         "<td><div align=\"center\" class=\"style44\" id=\"img3\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
         "<td><div align=\"center\" class=\"style44\" id=\"img4\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
         "<td><div align=\"center\" class=\"style44\" id=\"img5\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
         "<td><div align=\"center\" class=\"style44\" id=\"img6\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
      "</tr>"
    "</table>"
  "</div>"
  "<p>&nbsp;</p><div style=\"margin-left: 250px; margin-right: 10px;\">"
    "<table width=\"67%\" height=\"28%\" border=\"1\">"
      "<tr>"
        "<td width=\"25%\" height=\"30\">&nbsp;</td>"
        "<td width=\"11%\"><div align=\"center\" class=\"style43\"><strong>Cold Side Ground </strong></div></td>"
        "<td width=\"10%\"><div align=\"center\" class=\"style43\"><strong>Middle Ground </strong></div></td>"
        "<td width=\"10%\"><div align=\"center\" class=\"style43\"><strong>Hot Side Ground </strong></div></td>"
        "<td width=\"10%\"><div align=\"center\" class=\"style43\"><strong>Left Side Ambient </strong></div></td>"
        "<td width=\"9%\"><div align=\"center\" class=\"style43\"><strong>Right Side Ambient </strong></div></td>"
        "<td width=\"9%\"><div align=\"center\" class=\"style43\"><strong>Average Ambient </strong></div></td>"
      "</tr>"
      "<tr>"
        "<td height=\"10%\" nowrap=\"nowrap\" class=\"style42\"><strong>Temperature [\002] </strong></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"tmp1\"> \002 </div></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"tmp2\"> \002 </div></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"tmp3\"> \002 </div></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"tmp4\"> \002 </div></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"tmp5\"> \002 </div></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"tmp6\"> \002 </div></td>"
      "</tr>"
      "<tr>"
        "<td height=\"10%\" nowrap=\"nowrap\" class=\"style42\"><strong>Temperature Sensor Status </strong></td>"
        "<td><div align=\"center\" id=\"img7\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
        "<td><div align=\"center\" id=\"img8\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
        "<td><div align=\"center\" id=\"img9\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
        "<td><div align=\"center\" id=\"img10\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
        "<td><div align=\"center\" id=\"img11\"><img src= \"\002\" alt=  \"\002\" ></div></td>"
         "<td></td>"
      "</tr>"
      "<tr>"
        "<td height=\"28\" nowrap=\"nowrap\" class=\"style42\"><strong>Average Tank Humidity</strong></td>"
        "<td colspan=\"3\"><div align=\"center\" class=\"style44\" id=\"hum1\"> \002 %</div></td>"
       "</tr>"
     "</table>"
   "</div>"
 "</div>"
 "</center>"
 "</body>";

/********************************************
PAGE 2 DATA
********************************************/

PROGMEM char const http_uri2[] = "/page2";
PROGMEM char const content_title2[] = "";
PROGMEM char const content_page2[] = ""
"<body>"
"<center>"
"<div class=\"wrapper\"><div id=\"title\"><p><span id=\"hello\">&nbsp;</span></p><div id=\"attributes\">"
"<table width=\"100%\" border=\"0\" bordercolor=\"#FFFFFF\" bgcolor=\"#0066FF\">"
  "<tr>"
    "<td width=\"271\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"version\">Firmware Version: \002 </span></div></td>"
    "<td width=\"359\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"builddate\">Ip Address: \002 </span></div></td>"
    "<td width=\"191\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"date\"> \002 </span></div></td>"
    "<td width=\"176\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"time\"> \002 </span></div></td>"
  "</tr>"
"</table>"
"</div></div>"
"<div id=\"menu\">"
  "<a href=\"/\">System Overview</a>"
  "<a href=\"/page2\">Temperature Adjust</a>"
  "<a href=\"/page3\">Humidity Adjust</a>"
  "<a href=\"/page4\">Date/Time Adjust</a>"
  "<a href=\"/page5\">Data Logging Adjust</a>"
  "<a href=\"/page6\">View Recorded Data</a>"
  "<a href=\"/page7\">I/O Setup</a>"
  "<a href=\"/page8\">Network Setup</a>"
  "<a href=\"/page9\">System Information</a></div><div></div>"
"<!-- content -->"
"<center><b><font size = 10>Automated Reptile Environment Control System<br>Adjust Temperatures</font></b></center>"
"<form action=\"/page2\" method=\"POST\">"
  "<p>&nbsp;</p><div style=\"margin-left: 250px; margin-right: 10px;\">"
    "<table width=\"67%\" height=\"28%\" border=\"1\">"
      "<tr>"
        "<td colspan=\"5\"><center><b>Temperatures must be between \002<br>All settings will be saved to memory and will persist between power outage</b></center></td>"
      "</tr>"
      "<tr>"
        "<td width=\"25%\" height=\"30\">&nbsp;</td>"
        "<td width=\"11%\"><div align=\"center\" class=\"style43\"><strong>Cold Side Ground </strong></div></td>"
        "<td width=\"10%\"><div align=\"center\" class=\"style43\"><strong>Middle Ground </strong></div></td>"
        "<td width=\"10%\"><div align=\"center\" class=\"style43\"><strong>Hot Side Ground </strong></div></td>"
        "<td width=\"10%\"><div align=\"center\" class=\"style43\"><strong>Average Ambient </strong></div></td>"
        "</tr><tr><td height=\"10%\" nowrap=\"nowrap\" class=\"style42\"><strong>Day Time Temperatures</strong></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"ts1\">"
          "<table>"
          "\002"
            "<tr>"
              "<td>ON:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"1\" value= \"\002\" ></td>"
            "</tr>"
            "\002"
            "<tr>"
              "<td>OFF:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"2\" value = \"\002\" ></td>"
            "</tr>"
          "</table>"
        "</div></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"ts2\">"
          "<table>"
          "\002"
            "<tr>"
              "<td>ON:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"3\" value= \"\002\" ></td>"
            "</tr>"
            "\002"
            "<tr>"
              "<td>OFF:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"4\" value = \"\002\" ></td>"
            "</tr>"
          "</table>"
        "</div></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"ts3\">"
          "<table>"
          "\002"
            "<tr>"
              "<td>ON:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"5\" value= \"\002\" ></td>"
            "</tr>"
            "\002"
            "<tr>"
              "<td>OFF:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"6\" value = \"\002\" ></td>"
            "</tr>"
          "</table>"
        "</div></td>"
        "<td><div align=\"center\" class=\"style44\" id=\"ts4\">"
          "<table>"
          "\002"
            "<tr>"
              "<td>ON:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"7\" value= \"\002\" ></td>"
            "</tr>"
            "\002"
            "<tr>"
              "<td>OFF:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"8\" value = \"\002\" ></td>"
            "</tr>"
          "</table>"
        "</div></td>"
      "</tr>"
      "<tr>"
        "<td height=\"10%\" nowrap=\"nowrap\" class=\"style42\"><strong>Night Time Temperatures</strong></td>"
        "<td><div align=\"center\" id=\"tstat1\">"
          "<table>"
          "\002"
            "<tr>"
              "<td>ON:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"9\" value= \"\002\" ></td>"
            "</tr>"
            "\002"
            "<tr>"
              "<td>OFF:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"10\" value = \"\002\" ></td>"
            "</tr>"
          "</table>"
        "</div></td>"
        "<td><div align=\"center\" id=\"tstat2\">"
          "<table>"
          "\002"
            "<tr>"
              "<td>ON:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"11\" value= \"\002\" ></td>"
            "</tr>"
            "\002"
            "<tr>"
              "<td>OFF:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"12\" value = \"\002\" ></td>"
            "</tr>"
          "</table>"
        "</div></td>"
        "<td><div align=\"center\" id=\"tstat3\">"
          "<table>"
          "\002"
            "<tr>"
              "<td>ON:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"13\" value= \"\002\" ></td>"
            "</tr>"
            "\002"
            "<tr>"
              "<td>OFF:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"14\" value = \"\002\" ></td>"
            "</tr>"
          "</table>"
        "</div></td>"
        "<td><div align=\"center\" id=\"tstat4\">"
          "<table>"
          "\002"
            "<tr>"
              "<td>ON:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"15\" value= \"\002\" ></td>"
            "</tr>"
            "\002"
            "<tr>"
              "<td>OFF:</td>"
              "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"16\" value = \"\002\" ></td>"
            "</tr>"
          "</table>"
        "</div>"
      "</td>"
    "</tr>"
  "</table>"
  "<br>"
  "<table"
    "<tr>"
      "<td>Choose Temperature Scale (Fahrenheit or Celsius)</td>"
      "<td>"
        "<select name=\"17\">"
          "<option value=\"1\" \002 >Fahrenheit</option>"
          "<option value=\"2\" \002 >Celsius</option>"
        "</select>"
        "<br><br>"
        "Please Note: When changing the temperature scale, the ON/OFF settings must be updated accordingly<br>"
      "</td>"
    "</tr>"
   "</table>"
  "<center><input type=submit value=Submit></center>"
"</div></div>"
"<input type=hidden name=\"99\" value=\"%\">"
"</form>"
"</center>"
"</body>";

/********************************************
PAGE 3 DATA
********************************************/

PROGMEM char const http_uri3[] = "/page3";
PROGMEM char const content_title3[] = "";
PROGMEM char const content_page3[] = ""
"<body>"
"<center>"
"<div class=\"wrapper\"><div id=\"title\"><p><span id=\"hello\">&nbsp;</span></p><div id=\"attributes\">"
"<table width=\"100%\" border=\"0\" bordercolor=\"#FFFFFF\" bgcolor=\"#0066FF\">"
  "<tr>"
    "<td width=\"271\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"version\">Firmware Version: \002</span></div></td>"
    "<td width=\"359\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"builddate\">Ip Address: \002</span></div></td>"
    "<td width=\"191\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"date\"> \002 </span></div></td>"
    "<td width=\"176\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"time\"> \002 </span></div></td>"
  "</tr>"
"</table>"
"</div></div>"
"<div id=\"menu\">"
  "<a href=\"/\">System Overview</a>"
  "<a href=\"/page2\">Temperature Adjust</a>"
  "<a href=\"/page3\">Humidity Adjust</a>"
  "<a href=\"/page4\">Date/Time Adjust</a>"
  "<a href=\"/page5\">Data Logging Adjust</a>"
  "<a href=\"/page6\">View Recorded Data</a>"
  "<a href=\"/page7\">I/O Setup</a>"
  "<a href=\"/page8\">Network Setup</a>"
  "<a href=\"/page9\">System Information</a></div><div></div>"
  "<!-- content -->"
  "<center><b><font size = 10>Automated Reptile Environment Control System<br>Adjust Humidity</font></b></center><br>"
  "<form action=page3 method=POST>"
  	"<p>&nbsp;</p>"
  	"<div style=\"margin-left: 250px; margin-right: 10px;\"><table width=\"67%\" height=\"28%\" border=\"1\">"  
  	  "<tr>"
  	    "<td colspan=\"2\"><center>Minimum humidity level is 10% maximum hmidity level is 90%<br>All settings will be saved to memory and will persist between power outage</center></td>"
  	  "</tr>"
  	  "<tr>"
  		"<td height=\"10%\" nowrap=\"nowrap\" class=\"style42\"><strong>Day Time Humidity %</strong></td>"
  		"<td><div align=\"center\" class=\"style44\" id=\"ts1\">"
                  "<table>"
                    "\002"
                    "<tr>"
                      "<td>ON:</td>"
                        "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"1\" value=\"\002\"></td>"
                    "</tr>"
                    "\002"
                    "<tr>"
                        "<td>OFF:</td><td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"2\" value = \"\002\"></td>"
                    "</tr>"
                  "</table></div>"
                 "</td>"
  	  "</tr>"
  	  "<tr>"
  		"<td height=\"10%\" nowrap=\"nowrap\" class=\"style42\"><strong>Night Time Humidity %</strong></td>"
  		"<td><div align=\"center\" id=\"tstat1\">"
                  "<table>"
                  "\002"
                    "<tr>"
                      "<td>ON:</td>"
                      "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"3\" value=\"\002\"></td>"
                    "</tr>"
                    "\002"
                    "<tr>"
                      "<td>OFF:</td>"
                      "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"4\" value = \"\002\"></td>"
                    "</tr>"
                  "</table></div>"
                "</td>"
  	  "</tr>"
  	"</table>"
  	"<br>"
  	"<center><input type=submit value=Submit></center>"
  	"</div>"
  "</div>"
  "<input type=hidden name=\"99\" value=\"%\">"
  "</form>"
  "</center>"
  "</body>";

/********************************************
PAGE 4 DATA
********************************************/

PROGMEM char const http_uri4[] = "/page4";
PROGMEM char const content_title4[] = "";
PROGMEM char const content_page4[] = ""
"<body>"
"<center>"
"<div class=\"wrapper\">"
  "<div id=\"title\">"
    "<p><span id=\"hello\">&nbsp;</span></p>"
	"<div id=\"attributes\">"
	  "<table width=\"100%\" border=\"0\" bordercolor=\"#FFFFFF\" bgcolor=\"#0066FF\">"
			"<tr>"
			  "<td width=\"271\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"version\">Firmware Version: \002</span></div></td>"
   			  "<td width=\"359\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"builddate\">Ip Address: \002</span></div></td>"
			  "<td width=\"191\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"date\"> \002 </span></div></td>"
			  "<td width=\"176\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"time\"> \002 </span></div></td>"
			"</tr>"
	  "</table>"
		"</div>"
	"</div>"
	"<div id=\"menu\">"
  "<a href=\"/\">System Overview</a>"
  "<a href=\"/page2\">Temperature Adjust</a>"
  "<a href=\"/page3\">Humidity Adjust</a>"
  "<a href=\"/page4\">Date/Time Adjust</a>"
  "<a href=\"/page5\">Data Logging Adjust</a>"
  "<a href=\"/page6\">View Recorded Data</a>"
  "<a href=\"/page7\">I/O Setup</a>"
  "<a href=\"/page8\">Network Setup</a>"
  "<a href=\"/page9\">System Information</a></div><div>"
"<!-- content -->"
"<center><b><font size = 10>Automated Reptile Environment Control System<br>Adjust Date / Time Settings</font></b></center><br>"
"<form action=page4 method=POST>"
	"<p>&nbsp;</p>"
	"<div style=\"margin-left: 250px; margin-right: 10px;\"><table width=\"67%\" height=\"28%\" border=\"1\">"  
	  "<tr>"
	    "<td><center>"
                "<strong>Enter the current date</strong><br>"
                 "Month: "
                  "<select name=\"1\">"
                    "<option value=\"1\" \002 >January</option>"
                    "<option value=\"2\" \002 >February</option>"
                    "<option value=\"3\" \002 >March</option>"
                    "<option value=\"4\" \002 >April</option>"
                    "<option value=\"5\" \002 >May</option>"
                    "<option value=\"6\" \002 >June</option>"
                    "<option value=\"7\" \002 >July</option>"
                    "<option value=\"8\" \002 >August</option>"
                    "<option value=\"9\" \002 >September</option>"
                    "<option value=\"10\" \002 >October</option>"
                    "<option value=\"11\" \002 >November</option>"
                    "<option value=\"12\" \002 >December</option>"
                  "</select>   ||   "
                 "Day: </strong>"
                  "<select name=\"2\">"
                    "<option value=\"1\" \002 >1</option>"
                    "<option value=\"2\" \002 >2</option>"
                    "<option value=\"3\" \002 >3</option>"
                    "<option value=\"4\" \002 >4</option>"
                    "<option value=\"5\" \002 >5</option>"
                    "<option value=\"6\" \002 >6</option>"
                    "<option value=\"7\" \002 >7</option>"
                    "<option value=\"8\" \002 >8</option>"
                    "<option value=\"9\" \002 >9</option>"
                    "<option value=\"10\" \002 >10</option>"
                    "<option value=\"11\" \002 >11</option>"
                    "<option value=\"12\" \002 >12</option>"
                    "<option value=\"13\" \002 >13</option>"
                    "<option value=\"14\" \002 >14</option>"
                    "<option value=\"15\" \002 >15</option>"
                    "<option value=\"16\" \002 >16</option>"
                    "<option value=\"17\" \002 >17</option>"
                    "<option value=\"18\" \002 >18</option>"
                    "<option value=\"19\" \002 >19</option>"
                    "<option value=\"20\" \002 >20</option>"
                    "<option value=\"21\" \002 >21</option>"
                    "<option value=\"22\" \002 >22</option>"
                    "<option value=\"23\" \002 >23</option>"
                    "<option value=\"24\" \002 >24</option>"
                    "<option value=\"25\" \002 >25</option>"
                    "<option value=\"26\" \002 >26</option>"
                    "<option value=\"27\" \002 >27</option>"
                    "<option value=\"28\" \002 >28</option>"
                    "<option value=\"29\" \002 >29</option>"
                    "<option value=\"30\" \002 >30</option>"
                    "<option value=\"31\" \002 >31</option>"
                  "</select>   ||   "
                 "Year: "
                  "<select name=\"3\">"
                    "<option value=\"12\" \002 >2012</option>"
                    "<option value=\"13\" \002 >2013</option>"
                    "<option value=\"14\" \002 >2014</option>"
                    "<option value=\"15\" \002 >2015</option>"
                    "<option value=\"16\" \002 >2016</option>"
                    "<option value=\"17\" \002 >2017</option>"
                    "<option value=\"18\" \002 >2018</option>"
                    "<option value=\"19\" \002 >2019</option>"
                    "<option value=\"20\" \002 >2020</option>"
                    "<option value=\"21\" \002 >2021</option>"
                    "<option value=\"22\" \002 >2022</option>"
                    "<option value=\"23\" \002 >2023</option>"
                    "<option value=\"24\" \002 >2024</option>"
                    "<option value=\"25\" \002 >2025</option>"
                    "<option value=\"26\" \002 >2026</option>"
                    "<option value=\"27\" \002 >2027</option>"
                    "<option value=\"28\" \002 >2028</option>"
                    "<option value=\"29\" \002 >2029</option>"
                    "<option value=\"30\" \002 >2030</option>"
                  "</select><br><br>"
                "Day of the Week: "
              "<select name=\"4\">"
              "<option value=\"1\" \002 >Sunday</option>"
              "<option value=\"2\" \002 >Monday</option>"
              "<option value=\"3\" \002 >Tuesday</option>"
              "<option value=\"4\" \002 >Wednesday</option>"
              "<option value=\"5\" \002 >Thursday</option>"
              "<option value=\"6\" \002 >Friday</option>"
              "<option value=\"7\" \002 >Saturday</option>"
              "</select>   ||   "
            "Time Zone: "
              "<select name=\"5\">"
              "<option value=\"-12\" \002 >(UTC-12:00) International Date Line West</option>"
              "<option value=\"-11\" \002 >(UTC-11:00) Coordinated Universal Time-11</option>"
              "<option value=\"-10\" \002 >(UTC-10:00) Hawaii</option>"
              "<option value=\"-9\" \002 >(UTC-9:00) Alaska</option>"
              "<option value=\"-8\" \002 >(UTC-8:00) Pacific Time (US & Canada)</option>"
              "<option value=\"-7\" \002 >(UTC-7:00) Mountain Time (US & Canada)</option>"
              "<option value=\"-6\" \002 >(UTC-6:00) Central Time (US & Canada)</option>"
              "<option value=\"-5\" \002 >(UTC-5:00) Eastern Time (US & Canada)</option>"
              "<option value=\"-4\" \002 >(UTC-4:00) Atlantic Time (Canada)</option>"
              "<option value=\"-2\" \002 >(UTC-2:00) Coordinated Universal Time-02</option>"
              "<option value=\"0\" \002 >(UTC) Coordinated Universal Time</option>"
              "<option value=\"1\" \002 >(UTC+1)</option>"
              "<option value=\"2\" \002 >(UTC+2)</option>"
              "<option value=\"3\" \002 >(UTC+3)</option>"
              "<option value=\"4\" \002 >(UTC+4)</option>"
              "<option value=\"5\" \002 >(UTC+5)</option>"
              "<option value=\"6\" \002 >(UTC+6)</option>"
              "<option value=\"7\" \002 >(UTC+7)</option>"
              "<option value=\"8\" \002 >(UTC+8)</option>"
              "<option value=\"9\" \002 >(UTC+9)</option>"
              "<option value=\"10\" \002 >(UTC+10)</option>"
              "<option value=\"11\" \002 >(UTC+11)</option>"
              "<option value=\"12\" \002 >(UTC+12)</option>"
              "<option value=\"13\" \002 >(UTC+13)</option>"
              "</select><br><br>"
            " Update Time from online NTP server? <select name=\"6\"><option value=\"0\">NO</option><option value=\"1\">YES</option> <br>Please Note: May take few seconds before system responds again"
            "</center></td>"
          "</tr>"
	"</table>"
	"<br><br>"
	"<table width=\"67%\" height=\"28%\" border=\"1\"> " 
	 " <tr>"
	    "<td colspan=\"2\"><center>Configure the On / Off time for the UV Light<br>When the light is on the system is in \"Day Time Mode\"<br>When the light is off the system is in \"Night Time Mode\"</center></td>"
	  "</tr>"
	  "<tr>"
		"<td height=\"10%\" nowrap=\"nowrap\" class=\"style42\"><strong>UV Light ON / OFF Time</strong></td>"
		"<td><div align=\"center\" class=\"style44\" id=\"ts1\">"
                  "<table>"
                    "<tr>"
                      "<td></td>"
                      "<td>Hour</td>"
                      "<td>Minuets</td>"
                      "<td>Seconds</td>"
                    "</tr>"
                    "<tr>"
                    "\002"
                      "<td>ON:</td>"
                      "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"7\" value=\"\002\"></td>"
                      "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"8\" value=\"\002\"></td>"
                      "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"9\" value=\"\002\"></td>"
                    "</tr>"
                    "<tr>"
                    "\002"
                      "<td>OFF:</td>"
                      "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"10\" value = \"\002\"></td>"
                      "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"11\" value=\"\002\"></td>"
                      "<td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"12\" value=\"\002\"></td>"
                    "</tr>"
                  "</table></div>"
                "</td>"
	  "</tr>"
	"</table>"
	"<br>"
	"<center><input type=submit value=Submit></center>"
	"</div>"
"</div>"
"<input type=hidden name=\"99\" value=\"%\">"
"</form>"
"</center>"
"</body>";

/********************************************
PAGE 5 DATA
********************************************/

PROGMEM char const http_uri5[] = "/page5";
PROGMEM char const content_title5[] = "";
PROGMEM char const content_page5[] = ""
"<body>"
"<center>"
"<div class=\"wrapper\">"
  "<div id=\"title\">"
    "<p><span id=\"hello\">&nbsp;</span></p>"
	"<div id=\"attributes\">"
	  "<table width=\"100%\" border=\"0\" bordercolor=\"#FFFFFF\" bgcolor=\"#0066FF\">"
			"<tr>"
			  "<td width=\"271\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"version\">Firmware Version: \002</span></div></td>"
   			  "<td width=\"359\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"builddate\">Ip Address: \002</span></div></td>"
			  "<td width=\"191\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"date\"> \002 </span></div></td>"
			  "<td width=\"176\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"time\"> \002 </span></div></td>"
			"</tr>"
	  "</table>"
		"</div>"
	"</div>"
	"<div id=\"menu\">"
  "<a href=\"/\">System Overview</a>"
  "<a href=\"/page2\">Temperature Adjust</a>"
  "<a href=\"/page3\">Humidity Adjust</a>"
  "<a href=\"/page4\">Date/Time Adjust</a>"
  "<a href=\"/page5\">Data Logging Adjust</a>"
  "<a href=\"/page6\">View Recorded Data</a>"
  "<a href=\"/page7\">I/O Setup</a>"
  "<a href=\"/page8\">Network Setup</a>"
  "<a href=\"/page9\">System Information</a></div><div></div>"
"<!-- content -->"
"<center><b><font size = \"10\">Automated Reptile Environment Control System<br>Data Logging Adjust</font></b></center><br>"
"<form action=\"page5\" method=\"POST\">"
	"<p>&nbsp;</p>"
	"<div style=margin-left: 250px; margin-right: 10px;><center>"
	"<table width=\"25%\" height=\"28%\" border=\"1\">"  
	     "<tr>"
	     	"<td align = \"center\">"
	     		"<table border = \"0\">"
	     			"  \002  "
					"<tr>"
					    "<td colspan = \"2\" align = \"center\">SD Card Type:  \002  Formatted in FAT  \002  </td>"
					"</tr>"
					"<tr>"
						"<td colspan = \"2 valign=\"top\" style=\"border:1px solid black\"></td>"
					"</tr>"
				    "<tr>"
					    "<td rowspan = \"2\" align = \"center\" width = \"50%\">Total SD Card Space: </td>"
						"<td width = \"50%\">  \002  Kilobytes (KB)</td>"
					"<tr>"
						"<td width = \"50%\">  \002  Megabytes (MB)</td>"
					"</tr>"
					"<tr>"
						"<td colspan = \"2\" valign=\"top\" style=\"border:1px solid black\"></td>"
					"</tr>"
					"<tr>"
						"<td rowspan = \"2\" align = \"center\" width = \"50%\">SD Card Space Used: </td>"
						"<td width = \"50%\">  \002  Kilobytes (KB)</td>"
					"</tr>"
					"<tr>"
						"<td width = \"50%\">  \002  Megabytes (MB)</td>"
					"</tr>"
					"<tr>"
						"<td colspan = \"2\" valign=\"top\" style=\"border:1px solid black\"></td>"
					"</tr>"
					"<tr>"
					    "<td align = \"center\" colspan = \"2\">"
					    	"<table border = \"0\" align = \"center\">"
					    		"<tr>"
					    			"<td></td>"
					    		"</tr>"
					    		"<tr>"
					    			"<td align = \"center\">Percentage of SD card space utilized</td>"
					    		"</tr>"
					    		"<tr>"
					    			"<td>"
								    	"<div style=\"width:300px;padding:2px;background-color:grey;border:1px solid blacktext-align:left\">"
							    		"<div style=\"width:  \002  background-color:blue;\">_"
							    		"</div>"
							  			"</div>"
							  			"<center>  \002  %</center>"
							  		"</td>"
							  	"</tr>"
							"</table>"
					    "</td>"
					"</tr>"
				"</table>"
				"<table border=\"1\">" 
					"<tr>"
						"<td colspan = \"2\" align = \"center\">Data Logging Enabled or Disbaled<br>Note: Data logging is disbaled by default and the settings are not persistent between power outages or system resets</td>"
					"</tr>"
					"<tr>"
						"<td align = \"center\" width=\"50%\">"
							"<select name = \"1\">"
  								"<option value=\"1\"  \002  >Enabled</option>"
  								"<option value=\"0\"  \002  >Disabled</option>"
							"</select>" 
						"</td>"
						"<td align = \"center\" width=\"50%\">" 
							"<select name = \"2\">"
  								"<option value=\"10\"  \002  >1 Sample every 10 seconds</option>"
  								"<option value=\"20\"  \002  >1 Sample every 20 seconds</option>"
  								"<option value=\"30\"  \002  >1 Sample every 30 seconds</option>"
  								"<option value=\"40\"  \002  >1 Sample every 40 seconds</option>"
  								"<option value=\"50\"  \002  >1 Sample every 50 seconds</option>"
  								"<option value=\"60\"  \002  >1 Sample every 60 seconds</option>"
							"</select>"
						"</td>"
					"</tr>"
					"<tr>"
						"<td colspan = \"2\" align = \"center\"><input type=\"submit\" value=\"Submit\"  \002  >"
                                                 "<input type=hidden name=\"99\" value=\"%\"></form></td>"
					"</tr>"
                                        "<tr>"
                                                "<td colspan = \"2\" align = \"center\"><br>To delete a log file, disable data logging, select the file name below, and click on \"Delete Selected File\"<br><br>"
                                                  "<form action=\"page5\" method=\"POST\">"
                                                  "<table border=\"0\">"
                                                    "<tr>"
                                                      "<td align = \"center\">  \002  </td>"
                                                    "</tr>"
                                                    "<tr>"
                                                      "<td align = \"center\"><br><input type=\"submit\" value=\"Delete Selected File\"  \002  ></td>"
                                                    "</tr>"
                                                  "</table>"
                                                  "</form>"
                                                "</td>"
                                        "</tr>"
				"</table>"
			"</td>"
		"</tr>"
	"</table>"
	"</center></div>"
"</center>"
"</body>";

/********************************************
PAGE 6 DATA
********************************************/

PROGMEM char const http_uri6[] = "/page6";
PROGMEM char const content_title6[] = "";
PROGMEM char const content_page6[] = ""
"<body>"
"<center>"
"<div class=\"wrapper\">"
  "<div id=\"title\">"
    "<p><span id=\"hello\">&nbsp;</span></p>"
	"<div id=\"attributes\">"
	  "<table width=\"100%\" border=\"0\" bordercolor=\"#FFFFFF\" bgcolor=\"#0066FF\">"
			"<tr>"
			  "<td width=\"271\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"version\">Firmware Version: \002</span></div></td>"
   			  "<td width=\"359\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"builddate\">Ip Address: \002</span></div></td>"
			  "<td width=\"191\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"date\"> \002 </span></div></td>"
			  "<td width=\"176\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"time\"> \002 </span></div></td>"
			"</tr>"
	  "</table>"
		"</div>"
	"</div>"
	"<div id=\"menu\">"
  "<a href=\"/\">System Overview</a>"
  "<a href=\"/page2\">Temperature Adjust</a>"
  "<a href=\"/page3\">Humidity Adjust</a>"
  "<a href=\"/page4\">Date/Time Adjust</a>"
  "<a href=\"/page5\">Data Logging Adjust</a>"
  "<a href=\"/page6\">View Recorded Data</a>"
  "<a href=\"/page7\">I/O Setup</a>"
  "<a href=\"/page8\">Network Setup</a>"
  "<a href=\"/page9\">System Information</a></div><div></div>"
"<!-- content -->"
"<center><b><font size = \"10\">Automated Reptile Environment Control System<br>View Recorded Data</font></b></center><br>"
	"<p>&nbsp;</p>"
	"<div style=margin-left: 250px; margin-right: 10px;><center><strong>Never remove the SD card without removing power to the system<br>Corruption of the SD card and its contents may result</strong><br><br>Files Located on SD Card<br>Click on a file name to view the data in a new window<br><br>Please allow time for log files to download. Download time may be as high as ten minutes per file<br><br>"
	"\002"
        "</center>"
         "</div>"
         "</center>"
         "</body>";

/********************************************
PAGE 7 DATA
********************************************/

PROGMEM char const http_uri7[] = "/page7";
PROGMEM char const content_title7[] = "";
PROGMEM char const content_page7[] = ""
"<body>"
"<center>"
"<div class=\"wrapper\">"
  "<div id=\"title\">"
    "<p><span id=\"hello\">&nbsp;</span></p>"
	"<div id=\"attributes\">"
	  "<table width=\"100%\" border=\"0\" bordercolor=\"#FFFFFF\" bgcolor=\"#0066FF\">"
			"<tr>"
			  "<td width=\"271\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"version\">Firmware Version: \002 </span></div></td>"
   			  "<td width=\"359\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"builddate\">Ip Address: \002 </span></div></td>"
			  "<td width=\"191\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"date\"> \002 </span></div></td>"
			  "<td width=\"176\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"time\"> \002 </span></div></td>"
			"</tr>"
	  "</table>"
		"</div>"
	"</div>"
	"<div id=\"menu\">"
  "<a href=\"/\">System Overview</a>"
  "<a href=\"/page2\">Temperature Adjust</a>"
  "<a href=\"/page3\">Humidity Adjust</a>"
  "<a href=\"/page4\">Date/Time Adjust</a>"
  "<a href=\"/page5\">Data Logging Adjust</a>"
  "<a href=\"/page6\">View Recorded Data</a>"
  "<a href=\"/page7\">I/O Setup</a>"
  "<a href=\"/page8\">Network Setup</a>"
  "<a href=\"/page9\">System Information</a></div><div></div>"
"<!-- content -->"
"<center><b><font size = \"10\">Automated Reptile Environment Control System<br>I/O Setup</font></b></center><br>"
"<form action= \"page7\" method= \"POST\">"
	"<p>&nbsp;</p>"
	"<div style=margin-left: 250px; margin-right: 10px;><center><table width= \"50%\" height= \"28%\" border= \"1\">"  
	     "<tr>"
	     	"<td colspan = \"6\"><center>Configure each relay to be either manually controlled or automatically controlled by the system<br>Please note: the relays default to automatic system control. Changes to settings do not persist between power outages or resets</center></td>"
	     "</tr>"
          "<tr>"
            "<td align = \"center\"><strong>Cold Side Heater<br>Relay 1</strong></td>"
            "<td align = \"center\"><strong>Middle Heater<br>Relay 2</strong></td>"
            "<td align = \"center\"><strong>Hot Side Heater<br>Relay 3</strong></td>"
            "<td align = \"center\"><strong>Heat Lamp<br>Relay 4</strong></td>"
            "<td align = \"center\"><strong>UV Light<br>Relay 5</strong></td>"
            "<td align = \"center\"><strong>Humidifier<br>Relay 6<strong></td>"
          "</tr>"
          "<tr>"
            "<td><center>"
		"<select name=\"1\">"
		  "<option value=\"1\" \002 >Manual Control</option>"
		  "<option value=\"0\" \002 >System Auto Control</option>"
		"</select>"
	    "</center></td>"
            "<td><center>"
		  "<select name=\"2\">"
  		    "<option value=\"1\" \002 >Manual Control</option>"
  		    "<option value=\"0\" \002 >System Auto Control</option>"
		  "</select>"
	    "</center></td>"
	    "<td><center>"
		   "<select name=\"3\">"
		     "<option value=\"1\" \002 >Manual Control</option>"
		     "<option value=\"0\" \002 >System Auto Control</option>"
		   "</select>"
	    "</center></td>"
            "<td><center>"
		    "<select name=\"4\">"
		      "<option value=\"1\" \002 >Manual Control</option>"
		      "<option value=\"0\" \002 >System Auto Control</option>"
		    "</select>"
	    "</center></td>"
	    "<td><center>"
		    "<select name=\"5\">"
		      "<option value=\"1\"  \002  >Manual Control</option>"
		      "<option value=\"0\"  \002  >System Auto Control</option>"
		    "</select>"
	    "</center></td>"
            "<td><center>"
		    "<select name=\"6\">"
		      "<option value=\"1\"  \002  >Manual Control</option>"
		      "<option value=\"0\"  \002  >System Auto Control</option>"
		    "</select>"
	    "</center></td>"
          "</tr>"
          "<tr>"
          	"<td colspan = \"6\"><br><center><input type= \"submit\" value= \"Apply\"></center><br><br></td>"
    	  "</tr>"
	"<br><br>"
"<input type=hidden name=\"99\" value=\"%\">"
"</form>" 
  "<tr>"
    "<td align = \"center\">"
      "<form action=\"/page7\" method=\"POST\"><button name=\"CSGON\" value=  \002  type=submit  \002  >Turn Cold Side Heater<br><strong>  \002  </strong></button><input type=hidden name=\"99\" value=\"%\"></form>"
    "</td>"
    "<td align = \"center\">"
      "<form action=\"/page7\" method=\"POST\"><button name=\"MSGON\" value=  \002  type=submit  \002  >Turn Middle Heater<br><strong>  \002  </strong></button><input type=hidden name=\"99\" value=\"%\"></form>"
    "</td>"
    "<td align = \"center\">"
      "<form action=\"/page7\" method=\"POST\"><button name=\"HSGON\" value=  \002  type=submit  \002  >Turn Hot Side Heater<br><strong>  \002  </strong></button><input type=hidden name=\"99\" value=\"%\"></form>"
    "</td>"  
    "<td align = \"center\">"
      "<form action=\"/page7\" method=\"POST\"><button name=\"HLON\" value=  \002  type=submit  \002  >Turn Heat Lamp<br><strong>  \002  </strong></button><input type=hidden name=\"99\" value=\"%\"></form>"
    "</td>"
    "<td align = \"center\">"
      "<form action=\"/page7\" method=\"POST\"><button name=\"UVLON\" value=  \002  type=submit  \002  >Turn UV Light<br><strong>  \002  </strong></button><input type=hidden name=\"99\" value=\"%\"></form>"
    "</td>"
    "<td align = \"center\">"
      "<form action=\"/page7\" method=\"POST\"><button name=\"HUMON\" value=  \002  type=submit  \002  >Turn Humidifier<br><strong>  \002  </strong></button><input type=hidden name=\"99\" value=\"%\"></form>"
    "</td>"
  "</tr>"
  "</table>"
  "</div>"
  "</center>"
      "</body>";


/********************************************
PAGE 8 DATA
********************************************/

PROGMEM char const http_uri8[] = "/page8";
PROGMEM char const content_title8[] = "";
PROGMEM char const content_page8[] = ""
"<body>"
"<center>"
"<div class=\"wrapper\">"
  "<div id=\"title\">"
    "<p><span id=\"hello\">&nbsp;</span></p>"
	"<div id=\"attributes\">"
	  "<table width=\"100%\" border=\"0\" bordercolor=\"#FFFFFF\" bgcolor=\"#0066FF\">"
			"<tr>"
			  "<td width=\"271\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"version\">Firmware Version: \002 </span></div></td>"
   			  "<td width=\"359\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"builddate\">Ip Address: \002 </span></div></td>"
			  "<td width=\"191\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"date\"> \002 </span></div></td>"
			  "<td width=\"176\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"time\"> \002 </span></div></td>"
			"</tr>"
	  "</table>"
		"</div>"
	"</div>"
	"<div id=\"menu\">"
  "<a href=\"/\">System Overview</a>"
  "<a href=\"/page2\">Temperature Adjust</a>"
  "<a href=\"/page3\">Humidity Adjust</a>"
  "<a href=\"/page4\">Date/Time Adjust</a>"
  "<a href=\"/page5\">Data Logging Adjust</a>"
  "<a href=\"/page6\">View Recorded Data</a>"
  "<a href=\"/page7\">I/O Setup</a>"
  "<a href=\"/page8\">Network Setup</a>"
  "<a href=\"/page9\">System Information</a></div><div><div>"
"<!-- content -->"
"<center><b><font size = 10>Automated Reptile Environment Control System<br>Network Setup</font></b></center><br>"
"<form action=page8 method=POST>"
	"<p>&nbsp;</p>"
	"<div style=\"margin-left: 250px; margin-right: 10px;\"><center><table width=\"30%\" height=\"28%\" border=\"1\">"  
          "<tr>"
            "<td colspan = \"2\"><center>Changes in network settings will take effect after system reset or power cycle</center></td>"
          "</tr>"
          "\002"
	  "<tr>"
	    "<td>Static IP Address:</td><td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"1\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"2\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"3\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"4\" size = \"3\" value = \"\002\" \002 ></td>"
          "</tr>"
          "\002"
          "<tr>"
            "<td>Subnet Mask:</td><td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"5\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"6\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"7\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"8\" size = \"3\" value = \"\002\" \002 ></td>"
          "</tr>"
          "\002"
          "<tr>"
            "<td>Gateway:</td><td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"9\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"10\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"11\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"12\" size = \"3\" value = \"\002\" \002 ></td>"
          "</tr>"
          "\002"
          "<tr>"
            "<td>DNS Server:</td><td><input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"13\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"14\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"15\" size = \"3\" value = \"\002\" \002 >  .  <input type=\"text\"  align = \"MIDDLE\"  maxlength = \"3\" name=\"16\" size = \"3\" value = \"\002\" \002 ></td>"
          "</tr>"
          "<tr>"
            "<td colspan = \"2\"><input type=\"checkbox\" name=\"17\" value= \"1\" \002 >  Use DHCP</td>"
          "</tr>"
        "</table></center>"
	"<br>"
	"<center><input type=submit value=Submit></center>"
	"</div>"
"</div>"
"<input type=hidden name=\"99\" value=\"%\">"
"</form>"
"</center>"
"</body>";

/********************************************
PAGE 9 DATA
********************************************/

PROGMEM char const http_uri9[] = "/page9";
PROGMEM char const content_title9[] = "";
PROGMEM char const content_page9[] = ""
"<body>"
"<center>"
"<div class=\"wrapper\">"
  "<div id=\"title\">"
    "<p><span id=\"hello\">&nbsp;</span></p>"
	"<div id=\"attributes\">"
	  "<table width=\"100%\" border=\"0\" bordercolor=\"#FFFFFF\" bgcolor=\"#0066FF\">"
			"<tr>"
			  "<td width=\"271\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"version\">Firmware Version: \002 </span></div></td>"
   			  "<td width=\"359\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"builddate\">Ip Address: \002 </span></div></td>"
			  "<td width=\"191\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"date\"> \002 </span></div></td>"
			  "<td width=\"176\" bgcolor=\"#0066FF\"><div align=\"left\" class=\"style1 style3\"><span class=\"style46\" id=\"time\"> \002 </span></div></td>"
			"</tr>"
	  "</table>"
		"</div>"
	"</div>"
	"<div id=\"menu\">"
  "<a href=\"/\">System Overview</a>"
  "<a href=\"/page2\">Temperature Adjust</a>"
  "<a href=\"/page3\">Humidity Adjust</a>"
  "<a href=\"/page4\">Date/Time Adjust</a>"
  "<a href=\"/page5\">Data Logging Adjust</a>"
  "<a href=\"/page6\">View Recorded Data</a>"
  "<a href=\"/page7\">I/O Setup</a>"
  "<a href=\"/page8\">Network Setup</a>"
  "<a href=\"/page9\">System Information</a></div><div></div>"
"<!-- content -->"
"<center><b><font size = 10>Automated Reptile Environment Control System<br>System Information</font></b></center><br>"
"<p>&nbsp;</p>"
	"<div style=\"margin-left: 250px; margin-right: 10px;\"><center><table height=\"28%\" border=\"0\">"  
          "<tr>"
             "<td align=\"center\">System Uptime:</td><td align=\"center\"> \002  Years</td><td align=\"center\">||</td><td align=\"center\">    \002     Months</td><td align=\"center\">||</td><td align=\"center\">    \002    Days</td><td align=\"center\">||</td><td align=\"center\">    \002    Hours</td><td align=\"center\">||</td><td align=\"center\">    \002    Minutes</td><td align=\"center\">||</td><td align=\"center\">    \002    Seconds</td>"
          "</tr>"
          "<tr>"
            "<td align=\"center\" colspan=\"12\">&nbsp;</td>"
          "</tr>"
          "<tr>"
            "<td align=\"center\" colspan=\"12\">System MAC Address:    \002     :     \002     :     \002     :     \002     :     \002     :     \002     </td>"
          "</tr>"
          "<tr>"
            "<td align=\"center\" colspan=\"12\">&nbsp;</td>"
          "</tr>"
          "<tr>"
            "<td align=\"center\" colspan=\"12\">Sensor Malfunction Log:    \002     </td>"
          "</tr>"
          "<tr>"
            "<td align=\"center\" colspan=\"12\">&nbsp;</td>"
          "</tr>"
          "<tr>"
            "<td align=\"center\" colspan=\"12\">System RAM Free:    \002     Bytes</td>"
          "</tr>"
        "</table>"
"</center>"
"</body>";


/**********************************************************************************************************************
*                                   Strings stored in flash of the HTML we will be transmitting
***********************************************************************************************************************/

// HTTP Request message
PROGMEM char const content_404[] = "HTTP/1.1 404 Not Found\nServer: arduino\nContent-Type: text/html\n\n<html><head><title>Arduino Web Server - Error 404</title></head><body><h1>Error 404: Sorry, that page cannot be found!</h1></body>";
const char * const page_404[] PROGMEM = { content_404 }; // table with 404 page

const char * const contents_main[] PROGMEM = { content_main_header, content_main_top, content_main_menu, content_main_footer }; // table with 404 page
#define CONT_HEADER 0
#define CONT_TOP 1
#define CONT_MENU 2
#define CONT_FOOTER 3


// declare tables for the pages
const char * const contents_titles[] PROGMEM = { content_title1, content_title2, content_title3, content_title4, content_title5, content_title6, content_title7, content_title8, content_title9 }; // titles
const char * const contents_pages [] PROGMEM = { content_page1, content_page2, content_page3, content_page4, content_page5, content_page6, content_page7, content_page8, content_page9 }; // real content


/**********************************************************************************************************************
*                     Image strings and data stored in flash for the image UISs we will be transmitting
***********************************************************************************************************************/

// A Favicon is a little custom icon that appears next to a website's URL in the address bar of a web browser.
// They also show up in your bookmarked sites, on the tabs in tabbed browsers, and as the icon for Internet shortcuts
// on your desktop or other folders in Windows.
PROGMEM char const http_uri10[] = "/favicon.ico";    // favicon Request message
PROGMEM char const http_uri11[] = "/ledon.bmp";
PROGMEM char const http_uri12[] = "/ledoff.bmp";

PROGMEM char const content_image_header[] = "HTTP/1.1 200 OK\nServer: arduino\nContent-Length: \002\nContent-Type: image/\002\n\r\n";

PROGMEM const int content_favicon_data[] = {
             0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x10, 0x10, 0x10, 0x00, 0x01, 0x00, 0x04, 0x00, 0x28, 0x01, 0x00, 0x00, 0x16, 0x00,
             0x00, 0x00, 0x28, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00,
             0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
             0x00, 0x00, 0x80, 0x80, 0x00, 0x00, 0x80, 0x80, 0x80, 0x00, 0xC0, 0xC0, 0xC0, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00,
             0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
             0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
             0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x44, 0x44, 0x41, 0x00, 0x00, 0x14, 0x44, 0x44, 0x44, 0x41, 0x00, 0x00, 0x00, 0x00,
             0x14, 0x44, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x44, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x40, 0x23,
             0x33, 0x20, 0x02, 0x33, 0x32, 0x04, 0x12, 0x30, 0x00, 0x32, 0x23, 0x00, 0x03, 0x21, 0x03, 0x00, 0x00, 0x03, 0x30, 0x03,
             0x00, 0x30, 0x03, 0x03, 0x33, 0x03, 0x30, 0x33, 0x30, 0x30, 0x03, 0x00, 0x00, 0x03, 0x30, 0x03, 0x00, 0x30, 0x02, 0x30,
             0x00, 0x32, 0x23, 0x00, 0x03, 0x20, 0x10, 0x23, 0x33, 0x20, 0x02, 0x33, 0x32, 0x01, 0x40, 0x00, 0x00, 0x00, 0x00, 0x00,
             0x00, 0x04, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x14, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x44, 0x44, 0x41,
             0x00, 0x00, 0x00, 0x00, 0x14, 0x44, 0x44, 0x44, 0x41, 0x00, 0x00, 0x14, 0x44, 0x44, 0xF8, 0x1F, 0x00, 0x00, 0xE0, 0x07,
             0x00, 0x00, 0xC0, 0x03, 0x00, 0x00, 0x80, 0x01, 0x00, 0x00, 0x80, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
             0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x01,
             0x00, 0x00, 0x80, 0x01, 0x00, 0x00, 0xC0, 0x03, 0x00, 0x00, 0xE0, 0x07, 0x00, 0x00, 0xF8, 0x1F, 0x00, 0x00
             };
             
            

